In [43]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np

In [19]:
ratings=pd.read_excel("C:/Users/user/Downloads/01_제공데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_시청률 데이터.xlsx")
ratings.head(10)

,"NS SHOP+_일자별, 시간대별 시청률 (2019년)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 357,Unnamed: 358,Unnamed: 359,Unnamed: 360,Unnamed: 361,Unnamed: 362,Unnamed: 363,Unnamed: 364,Unnamed: 365,Unnamed: 366
0,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
5,02:04,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
6,02:05,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
7,02:06,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
8,02:07,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
9,02:08,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003

In [20]:
ratings=ratings.drop(ratings.index[1441])
ratings

,"NS SHOP+_일자별, 시간대별 시청률 (2019년)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 357,Unnamed: 358,Unnamed: 359,Unnamed: 360,Unnamed: 361,Unnamed: 362,Unnamed: 363,Unnamed: 364,Unnamed: 365,Unnamed: 366
0,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1436,01:55,0,0,0,0,0,0,0,0,0.004,...,0.013,0,0,0,0.015,0,0,0,0,0.004
1437,01:56,0,0,0,0,0.027,0,0,0,0,...,0.013,0,0,0,0.015,0,0,0,0,0.004
1438,01:57,0,0,0,0,0,0,0,0,0.004,...,0.013,0,0,0,0.015,0,0,0,0,0.004
1439,01:58,0,0,0,0,0,0,0,0,0.004,...,0.013,0.017,0,0,0.015,0,0,0.019,0,0.004
1440,01:59,0,0,0,0,0,0,0,0,0.004,...,0.013,0,0,0,0.015,0,0,0,0,0.004

In [22]:
tem=ratings
tem = tem.rename(columns=tem.iloc[0])

tem.head(10)

,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
0,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
5,02:04,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
6,02:05,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
7,02:06,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
8,02:07,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
9,02:08,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003

In [23]:
temp=ratings
temp = temp.rename(columns=temp.iloc[0])
temp = temp.drop(temp.index[0])

temp.head(10)

,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
5,02:04,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
6,02:05,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
7,02:06,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
8,02:07,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
9,02:08,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
10,02:09,0.014,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003

In [25]:
len(temp.columns)

367

In [28]:
temp['2019-01-01 to 2019-12-31']

1       0.003
2       0.003
3       0.004
4       0.004
5       0.004
        ...
1436    0.004
1437    0.004
1438    0.004
1439    0.004
1440    0.004
Name: 2019-01-01 to 2019-12-31, Length: 1440, dtype: object

In [29]:
del temp['2019-01-01 to 2019-12-31']

In [30]:
len(temp.columns)

366

In [39]:
temp
#여기까지 멀쩡한데 다음 열부터 moving average 제대로 작동 x

,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-22,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.012
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0,0.017,0,0,0,0,0,0
5,02:04,0,0,0,0,0,0,0,0,0,...,0,0,0,0.017,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1436,01:55,0,0,0,0,0,0,0,0,0.004,...,0,0.013,0,0,0,0.015,0,0,0,0
1437,01:56,0,0,0,0,0.027,0,0,0,0,...,0,0.013,0,0,0,0.015,0,0,0,0
1438,01:57,0,0,0,0,0,0,0,0,0.004,...,0,0.013,0,0,0,0.015,0,0,0,0
1439,01:58,0,0,0,0,0,0,0,0,0.004,...,0,0.013,0.017,0,0,0.015,0,0,0.019,0
1440,01:59,0,0,0,0,0,0,0,0,0.004,...,0,0.013,0,0,0,0.015,0,0,0,0

In [44]:
def moving_average(data_set, periods=3):
    weights = np.ones(periods) / periods
    return np.convolve(data_set, weights, mode='valid')

In [54]:
ma = moving_average(t0101, 3)
ma
ma=pd.DataFrame(ma)
ma

ma[ma[0]>0]
#465개
ma.count()

0    1438
dtype: int64

In [33]:
'''
t0101=temp.loc[:,1]
data=t0101.rolling(20).mean()
'''

'\nt0101=temp.loc[:,1]\ndata=t0101.rolling(20).mean()\n'

In [41]:
t0101=temp.iloc[:,1]
t0101
'''
data=t0101.rolling(20).mean()
data
'''

'\ndata=t0101.rolling(20).mean()\ndata\n'